Repository sveltestrap/sveltestrap, pull requests merged in 2023-12, with the labels that each got.

#8 📖 stories(docs): add Layout stories and docs
  .storybook/storybook.css
  src/Container/Container.d.ts
  src/Container/Container.mdx
  src/Container/Container.stories.svelte
  src/Container/Container.svelte
  src/Grid/Grid.mdx
  src/Grid/Grid.stories.svelte
Labels: Type: Documentation

#10 📖 stories(docs): add Progress & Spinner stories and docs
  .storybook/storybook.css
  src/Progress/Progress.d.ts
  src/Progress/Progress.mdx
  src/Progress/Progress.stories.svelte
  src/Progress/Progress.svelte
  src/Spinner/Spinner.d.ts
  src/Spinner/Spinner.mdx
  src/Spinner/Spinner.stories.svelte
  src/Spinner/Spinner.svelte
Labels: Type: Documentation

#12 🧹 refactor(docs): update Component source language
  src/Container/Container.mdx
  src/Grid/Grid.mdx
  src/Progress/Progress.mdx
  src/Spinner/Spinner.mdx
Labels: Type: Documentation

#11 📖 stories(docs): add Pagination stories and docs
  src/Pagination/Pagination.d.ts
  src/Pagination/Pagination.mdx
  src/Pagination/Pagination.stories.svelte
  src/Pagination/Pagination.svelte
Labels: Type: Documentation

#13 📖 stories(docs): add Form stories and docs
  .storybook/storybook.css
  src/FormGroup/FormGroup.mdx
  src/FormGroup/FormGroup.stories.svelte
  src/FormGroup/FormGroup.svelte
  src/Input/Input.mdx
  src/Input/Input.stories.svelte
  src/Input/Input.svelte
  src/InputGroup/InputGroup.mdx
  src/InputGroup/InputGroup.stories.svelte
  src/InputGroup/InputGroup.svelte
  src/Validation/Validation.mdx
  src/Validation/Validation.stories.svelte
Labels: Type: Documentation

#16 📖 stories(docs): add more stories and docs
  .storybook/storybook.css
  src/Card/Card.mdx
  src/Card/Card.stories.svelte
  src/Card/Card.svelte
  src/Fade/Fade.mdx
  src/Fade/Fade.stories.svelte
  src/Fade/Fade.svelte
  src/Icon/Icon.mdx
  src/Icon/Icon.stories.svelte
  src/Icon/Icon.svelte
  src/Tabs/Tabs.mdx
  src/Tabs/Tabs.stories.svelte
  src/Toast/Toast.mdx
  src/Toast/Toast.stories.svelte
  src/Toast/Toast.svelte
Labels: Type: Documentation

#17 🐛 fix(dropdown): update dropdown, dropdownitem and toggler #459
  README.md
  src/DropdownItem/DropdownItem.d.ts
  src/DropdownItem/DropdownItem.snap.js
  src/DropdownItem/DropdownItem.svelte
  src/DropdownMenu/DropdownMenu.d.ts
  src/DropdownMenu/DropdownMenu.snap.js
  src/DropdownMenu/DropdownMenu.svelte
  src/DropdownToggle/DropdownToggle.snap.js
  src/DropdownToggle/DropdownToggle.svelte
Labels: Type: Bug

#18 🐛 fix(popover): fix issue with hiding popover on outside click #418
  README.md
  src/Popover/Popover.d.ts
  src/Popover/Popover.mdx
  src/Popover/Popover.stories.svelte
  src/Popover/Popover.svelte
Labels: Status: WIP, Type: Bug, DO NOT MERGE

#19 📖 stories(ListGroup): add stories and documentation
  .storybook/storybook.css
  src/ListGroup/ListGroup.mdx
  src/ListGroup/ListGroup.stories.svelte
  src/ListGroup/ListGroup.svelte
Labels: Type: Documentation

#20 📖 stories(Tooltip): add stories and docs
  .storybook/storybook.css
  src/Tooltip/Tooltip.mdx
  src/Tooltip/Tooltip.stories.svelte
Labels: Type: Documentation

#22 stories(carousel): add stories and docs
  .storybook/storybook.css
  src/Carousel/Carousel.mdx
  src/Carousel/Carousel.stories.svelte
  src/Carousel/Carousel.svelte
Labels: Type: Documentation

#21 📖 stories(modal): add stories and docs
  .storybook/storybook.css
  src/Modal/Modal.mdx
  src/Modal/Modal.stories.svelte
  src/Modal/Modal.svelte
Labels: Type: Documentation

#24 📖 stories(dropdown): add stories and docs
  .storybook/storybook.css
  src/Dropdown/Dropdown.mdx
  src/Dropdown/Dropdown.stories.svelte
  src/Dropdown/Dropdown.svelte
Labels: Type: Documentation

#25 🧹 refactor(docs): fix minor grammar issues
  src/Alert/Alert.mdx
  src/Toast/Toast.mdx
  src/Toast/Toast.stories.svelte
Labels: Type: Refactor, Type: Documentation

#26 🏗 ci(integration): add playwright for integration tests
  .github/workflows/integration.yml
  .gitignore
  .lintstagedrc
  package.json
  playwright.config.ts
  pnpm-lock.yaml
  src/Accordion/Accordion.d.ts
  src/Accordion/Accordion.stories.svelte
  src/Accordion/Accordion.svelte
  src/AccordionHeader/AccordionHeader.snap.js
  src/AccordionHeader/AccordionHeader.svelte
  src/AccordionItem/AccordionItem.snap.js
  src/AccordionItem/AccordionItem.svelte
  tests/app/.gitignore
  tests/app/.npmrc
  tests/app/jsconfig.json
  tests/app/package.json
  tests/app/pnpm-lock.yaml
  tests/app/src/app.d.ts
  tests/app/src/app.html
  tests/app/src/routes/+page.svelte
  tests/app/static/favicon.png
  tests/app/svelte.config.js
  tests/app/vite.config.js
  tests/sveltestrap.spec.ts
Labels: Type: CI/CD

#27 🧪 chore(playwright): update playwright config and tests
  package.json
  playwright.config.js
  tests/app/src/routes/+page.svelte
  tests/snapshots/accordion/accordion.png
  tests/snapshots/alert/alert.png
  tests/snapshots/badge/badge.png
  tests/snapshots/breadcrumb/breadcrumb.png
  tests/snapshots/button-group/button-group.png
  tests/snapshots/button-toolbar/button-toolbar.png
  tests/snapshots/button/button.png
  tests/snapshots/card/card.png
  tests/snapshots/dropdown/dropdown.png
  tests/sveltestrap.spec.js
  tests/sveltestrap.spec.ts
Labels: Type: Tests

#28 🐛 fix(carousel): fix the disabling of previous nav when wrap has been disabled
  src/CarouselControl/CarouselControl.svelte
  src/utils.js
Labels: Priority: Low, Severity: Low, Type: Bug

#29 🐛 fix(bindings): swap event binding order for input and formcheck
  src/FormCheck/FormCheck.svelte
  src/Input/Input.svelte
Labels: Priority: Low, Severity: Low, Type: Bug

#31 📖 docs(storybook): update event and slot details
  .storybook/storybook.css
  src/Accordion/Accordion.stories.svelte
  src/Alert/Alert.mdx
  src/Alert/Alert.stories.svelte
  src/Badge/Badge.stories.svelte
  src/Breadcrumb/Breadcrumb.stories.svelte
  src/Button/Button.stories.svelte
  src/Card/Card.stories.svelte
  src/Carousel/Carousel.stories.svelte
  src/Carousel/Carousel.svelte
  src/Container/Container.stories.svelte
  src/Dropdown/Dropdown.stories.svelte
  src/FormGroup/FormGroup.mdx
  src/FormGroup/FormGroup.stories.svelte
  src/Input/Input.stories.svelte
  src/InputGroup/InputGroup.stories.svelte
  src/ListGroup/ListGroup.stories.svelte
  src/Modal/Modal.stories.svelte
  src/Nav/Nav.stories.svelte
  src/Navbar/Navbar.stories.svelte
  src/Offcanvas/Offcanvas.mdx
  src/Offcanvas/Offcanvas.stories.svelte
  src/Pagination/Pagination.stories.svelte
  src/Popover/Popover.mdx
  src/Popover/Popover.stories.svelte
  src/Progress/Progress.stories.svelte
  src/Table/Table.stories.svelte
  src/Toast/Toast.mdx
  src/Toast/Toast.stories.svelte
  src/Tooltip/Tooltip.stories.svelte
Labels: Type: Documentation

#35 🧹 refactor: Fix publint errors and build process
  package.json
  pnpm-lock.yaml
  postcss.config.js
  svelte.config.js
  tsconfig.json
  vite.config.js
  vitest.setup.js
Labels: Priority: Medium, Type: Refactor

#42 🐛 fix(types): update types with missing events
  src/AccordionItem/AccordionItem.d.ts
  src/Button/Button.d.ts
  src/ButtonDropdown/ButtonDropdown.d.ts
  src/Card/Card.d.ts
  src/DropdownItem/DropdownItem.d.ts
  src/Form/Form.d.ts
  src/FormCheck/FormCheck.d.ts
  src/Input/Input.d.ts
  src/ListGroupItem/ListGroupItem.d.ts
  src/ModalBackdrop/ModalBackdrop.d.ts
  src/NavbarBrand/NavbarBrand.d.ts
Labels: Priority: Medium, Severity: Medium, Type: Bug

#41 🧹 refactor(formgroup): add spacer prop with mb-3 as default for parity
  .storybook/storybook.css
  src/FormGroup/FormGroup.d.ts
  src/FormGroup/FormGroup.snap.js
  src/FormGroup/FormGroup.stories.svelte
  src/FormGroup/FormGroup.svelte
Labels: Type: Refactor
