Repository sveltestrap/sveltestrap, pull requests merged in 2024-01, with the labels that each got.

#46 🐛 fix(types): Export shared types to allow configurable component props with typescript.
  src/index.d.ts
Labels: Priority: Medium, Severity: Low, Type: Bug

#48 🐛 fix(select): set input value to undefined as default to prevent binding loop with input elements
  src/Input/Input.d.ts
  src/Input/Input.svelte
  src/index.d.ts
  src/shared.d.ts
Labels: Priority: Low, Severity: Low, Type: Bug

#45 ✨ feat(badges): add positioned badge support to badges
  src/Badge/Badge.d.ts
  src/Badge/Badge.mdx
  src/Badge/Badge.snap.js
  src/Badge/Badge.spec.js
  src/Badge/Badge.stories.svelte
  src/Badge/Badge.svelte
  src/index.d.ts
  src/shared.d.ts
Labels: Type: Feature, Priority: Low, Status: Review Needed, Type: Documentation

#52 🐛 fix(types): use correct ColumnProps in Label
  src/Col/Col.d.ts
  src/Col/index.d.ts
Labels: Type: Bug

#53 🧹 misc(cleanup): fixing jsdoc comments and prop types
  src/Card/Card.d.ts
  src/Figure/Figure.d.ts
  src/Figure/Figure.svelte
  src/Icon/Icon.svelte
  src/Image/Image.svelte
  src/Input/Input.d.ts
  src/Input/Input.mdx
  src/Input/Input.stories.svelte
  src/Input/Input.svelte
  src/InputGroup/InputGroup.svelte
  src/InputGroupText/InputGroupText.svelte
  src/Jumbotron/Jumbotron.svelte
  src/ListGroupItem/ListGroupItem.d.ts
  src/Toast/Toast.d.ts
  src/Toast/Toast.svelte
Labels: Priority: Low, Severity: Low, Type: Refactor

#54 🧹 refactor(input): add min/max props and dry up input logic
  README.md
  src/Input/Input.d.ts
  src/Input/Input.spec.js
  src/Input/Input.svelte
Labels: Priority: Low, Severity: Low, Type: Refactor, Type: Bug
