Repository sveltestrap/sveltestrap, pull requests merged in 2025-01, with the labels that each got.

#97 🐛 fix(carousel): use setInterval instead of setTimeout for cycling
  src/Carousel/Carousel.svelte
Labels: Priority: Medium, Type: Bug

#92 ✨ feat(popover): adding `auto` to the PopoverPlacement type.
  src/Popover/Popover.d.ts
  src/Popover/Popover.mdx
  src/Popover/Popover.snap.js
  src/Popover/Popover.spec.js
  src/Popover/Popover.stories.svelte
Labels: Priority: Low, Severity: Low, Type: Refactor, Type: Bug

#106 🐛 fix(figure): remove extraneous image and fix type def
  src/Figure/Figure.d.ts
  src/Figure/Figure.snap.js
  src/Figure/Figure.svelte
Labels: Priority: Low, Severity: Low, Type: Bug
